version: '3'

services: 
  frontend:
    container_name: frontend
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2018-09/personal-projects/bab/frontend:latest
    volumes:
      - frontend:/frontend
    environment:
     - NOED_ENV=development
    command: /bin/bash 'rm /frontend/* && mv /build/* /frontend/' 

volumes:
  frontend:

networks:
  default:
    external:
      name: bab