version: '3'

services: 
  frontend:
    container_name: frontend
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2018-09/personal-projects/bab/frontend:latest
    volumes:
      - frontend:/frontend
    environment:
     - NODE_ENV=development
    command: /bin/bash -c 'rm -rf /frontend/* && cp -r /app/build/* /frontend' 

volumes:
  frontend:
    external: true

networks:
  default:
    external:
      name: bab