version: '3'

services: 
  frontend:
    container_name: frontend
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2018-09/personal-projects/bab/frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports: 
      - '3000:3000'