export const types = {
    SET_TOKEN: 'SET_TOKEN',
    SET_ACTIVE_USER: 'SET_ACTIVE_USER',
    LOGOUT: 'LOGOUT',
    LOADING: 'LOADING',
    SET_CONTENT: 'SET_CONTENT',
    SET_AGENT_FILTER: 'SET_AGENT_FILTER',
    SET_AGENT_DETAIL: 'SET_AGENT_DETAIL',
    SET_USER_DETAIL: 'SET_USER_DETAIL',
    ACTIVATE_DEACTIVATE_AGENT: 'ACTIVATE_DEACTIVATE_AGENT',
}

export const baseAPIUrl = 'https://accessbrother.propulsion-learn.ch/backend/api/';